### ISSUE TITLE
App Template and UI Pkg - Primary Model Pinning

### ISSUE THREAD

**Issue by slathrop** [vuepointjs/pm-v1.0-beta#1]
### Tasks
- [x] Popup instruction msg on "create" for related models when primary not yet pinned
  - Allow "create" use-case for non-pinnable *primary* models (i.e., stand-alone entities)
  - Verify that model of pinned item matches the one required by FK
- [x] Conditional axios post obj for "create" (set foreign key, check if primary is pinnable)
- [x] Model metadata lookups
  - [x] Basic lookup of Name and FK for primary model given secondary model
  - [x] Also relations *and* whether primary for a secondary is actually marked as "pinnable"
- [x] Views menu reactive to change in pinned state (pseudo view "(Pinned)")
- [x] Grid Views reactive to filtered state based on pin
  - Filter expression must include 2 clauses
    - PK or FK, and
    - Archived=0
- [x] Applet launcher menu reactive to pinned state
  - ~~Change main icon~~
    - Tried mdi `mdi-account-settings` and looks OK, but also seems it may be too confusing to swap out waffle. Shelving idea for now.
  - Change arrangement of applet icon nav area, and
  - ~~Hide/show applet icons based on ability to create items (e.g., can't create a stand-alone item when a primary is pinned... so only show related item icons)~~
    - This isn't necessary or desirable on second thought... user should still be able to access and create stand-alone items
  - ~~Change primary icon~~ and add indicator of item that is pinned
  - Add unpin option reactively to allow unpinning from launcher
- [x] Testing, refactoring, documentation
- [x] Integrate template changes into a solution
