### ISSUE TITLE
API Template and LB Pkg - DB and LB Support for Timeline Data

### ISSUE THREAD

**Issue by slathrop** [vuepointjs/pm-v1.0-beta#10]
### Tasks
- [ ] Finish research on LB support for DB Views
- [ ] Implement DB View to consolidate history/timeline data
  - For a single, primary pinnable model, timeline of past related model data
  - DB View likely must have a surrogate primary key column for LB to work properly
- [ ] Implement API template dev ops script(s) for getting/updating LB model for DB View
  - [ ] Scripts should be re-runnable to sync changes to existing model when DB View changes
- [ ] Make model read only in LB
  - [ ] Implement model customizations to avoid creating/showing endpoints that allow writing
- [ ] Testing, refactoring, documentation
- [ ] Integrate template changes into a solution
