### ISSUE TITLE
App Template and UI Pkg - Implement Timeline UI

### ISSUE THREAD

**Issue by slathrop** [vuepointjs/pm-v1.0-beta#11]
### Background
- Assumes timeline support implemented in DB and LB
- Timeline UI would typically be shown:
  - In cases where a primary model (Contact/Party) has many relationships to time stamped data in secondary, related models (Notes, Calls, etc.)
  - Timeline UI would appear when user "pins" app to a particular Contact/Party as an alternative to simply filtering an item grid view to a single row

### Tasks
- [ ] Design Timeline component
- [ ] Implement Timeline component
- [ ] Add any required global state or metadata related to Timeline view
- [ ] Implement Timeline data fetching/caching logic
- [ ] Add reactive logic to items grid toolbar, items grid views menu, other existing UI elts that need to know/represent that a timeline is displayed
- [ ] Testing, refactoring, documentation
- [ ] Integrate template changes into a solution
