### ISSUE TITLE
App Template and UI Pkg - Applet Item Detail Form More Complete Support for Rendering all Field Types

### ISSUE THREAD

**Issue by slathrop** [vuepointjs/pm-v1.0-beta#12]
### Tasks
- [ ] Implement input of type number for int numeric types
- [ ] Implement money type inputs
- [ ] Implement dropdown for categorical value (simple lookup) types
- [ ] Implement date picker calendar for date types
- [ ] Implement datetime or time picker for time/datetime types
- [ ] Testing, refactoring, documentation
- [ ] Integrate template changes into a solution
