### ISSUE TITLE
App Template and UI Pkg - Applet Items Grid View Title Area Component

### ISSUE THREAD

**Issue by slathrop** [vuepointjs/pm-v1.0-beta#2]
### Background
- Users could get confused about "where they are" in an app due to uniformity in the look of applet grid views
  - Need to mitigate concerns over amount of navigation between "applets"
- Although a breadcrumb link trail *could* be considered, the more immediate, simple improvement would come from at-a-glance, prominent caption area above grid views

### Tasks
- [ ] Design caption area component based roughly on SharePoint and O365
- [ ] Implement design, use taxonomy
- [ ] Testing, refactoring, documentation
- [ ] Integrate template changes into a solution

### Next Steps
- Consider how the horizontal whitespace created to the right of the icon and title could be used
  - Heat map akin to GitHub contribution graph?
- Concerned that users familiar with SP may wonder why there is no menu/navigation in this area akin to SharePoint, which doesn't really apply here
