### ISSUE TITLE
App Template and UI Pkg - Quick Actions/Quick Steps Implementation

### ISSUE THREAD

**Issue by slathrop** [vuepointjs/pm-v1.0-beta#22]
### Background
- Users like more immediate, persistent on-screen "affordances"
  - Links/buttons/menus for taking actions immediately without having to navigate somewhere first
- "Quick Actions" would afford user the ability to add a new item to a secondary list (e.g., Comments) when the primary item (e.g., Contact/Party) is already pinned, with a focus on minimum-required data inputs to accomplish this
  - For example, user might be in Contact/Partys page but wants to quickly add a related Comment item without navigating to Comments list first
- "Quick Steps" would afford user the ability to kick-off a sequence of orchestrated actions that depend on one another, for example, when a primary item is *not* already pinned, walk user through sequence of "Quick Add" of Contact/Party then "Quick Add" of Comments item

### Tasks
- [ ] Design UI
  - Considering dockable launcher menu approach with additional context menus (on hover) and kbd shortcuts
    - [x] Discuss initial design ideas internally
  - Determine how UI elements might be factored into components
- [ ] Implement UI state mgmt
- [ ] Implement dockable launcher
- [ ] Implement context menus
- [ ] Implement quick entry popups
  - [ ] Implement metadata and helpers to identify item properties that are part of "quick add"
  - [ ] Implement stepper/wizard popups
- [ ] Implement axios data saving operations
- [ ] Implement kbd shortcuts
- [ ] Testing, refactoring, documentation
- [ ] Integrate template changes into a solution
