### ISSUE TITLE
API Template and LB Pkg - DB and LB Support for "Needs Attention" Data

### ISSUE THREAD

**Issue by slathrop** [vuepointjs/pm-v1.0-beta#23]
### Background
- The data for the "Needs Attention" implementation *could* come from a custom database view and associated LB model, similar to the Timeline feature
- This approach would be the most efficient, but has the drawback of not being immediately portable to future apps that are based on this framework (i.e., a custom view would have to written on app-by-app basis to activate this feature)
  - Unless of course we somehow automate the creation of the view and LB model at build-time and/or run-time... which is possible as well
- So the preferable approach for now (simplest, most portable) is to use the metadata on the front-end to drive polling of the API on an individual applet/endpoint basis. Under that approach, *this story becomes unnecessary*. Thus this story is only here for completeness/as a placeholder in the backlog. And estimates are not given.

### Tasks
- [ ] Implement DB View to consolidate data
- [ ] Implement API template dev ops script(s) for getting/updating LB model for DB View
  - [ ] Scripts should be re-runnable to sync changes to existing model when DB View changes
- [ ] Make model read only in LB
  - [ ] Implement model customizations to avoid creating/showing endpoints that allow writing
- [ ] Testing, refactoring, documentation
- [ ] Integrate template changes into a solution
