### ISSUE TITLE
App Template and UI Pkg - Reports/Views and "Needs Attention" Implementation

### ISSUE THREAD

**Issue by slathrop** [vuepointjs/pm-v1.0-beta#24]
### Background
- Applets need configurable tabular reports/views (which columns, filters, etc. to use for items grid)
- The "Needs Attention" feature is mostly a special case view for each applet
  - But with additional features such as applet icon badging, data polling, etc.
  - Filter is based on current status being in a defined set of values
- This story therefore also encompasses some additional work on overall support for reports/views config and UI

### Tasks
- [ ] Implement state mgmt and cache for needs attention counts
- [ ] Revisit metadata for view filters and account for ability to record "Needs Attention" filters
- [ ] Implement launcher UI
- [ ] Implement items grid toolbar and views menu UI
- [ ] Implement data polling
- [ ] Implement special case for pinned primary model (e.g., Contact/Party)
  - [ ] Data filter is obviously different
  - [ ] State mgmt and caching considerations
    - Can't really cache or poll down to individual item (e.g., Contact/Party) level
    - Therefore logic should change and UI feedback implemented to indicate badge data is being refreshed, for example
- [ ] Testing, refactoring, documentation
- [ ] Integrate template changes into a solution
