### ISSUE TITLE
Suite Template, UI Pkg - Implement Basic Suite Site

### ISSUE THREAD

**Issue by slathrop** [vuepointjs/pm-v1.0-beta#25]
### Background
- Basic Suite Site is needed simply to host the Admin Site if nothing else

### Tasks
- [ ] Create site from template
- [ ] Update automated build, incl. more fine-grained build trigger
- [ ] Config and packaging for cluster deployment
- [ ] Testing, refactoring, documentation
- [ ] Integrate template changes into a solution
