### ISSUE TITLE
Solution, Suite Template, Dev Ops - Initial Implementation for Admin Site

### ISSUE THREAD

**Issue by slathrop** [vuepointjs/pm-v1.0-beta#26]
### Background
- Admin site is part of Suite Site, so #25 is a prerequisite

### Tasks
- [ ] Refactor solution data schema for proper validation (see [this issue](https://github.com/netlify/netlify-cms/issues/467)) and more friendly breakdown of auto-generated CMS forms/screens
- [ ] Evaluate Netlify CMS 2.x
- [ ] Update automated build, incl. more fine-grained build trigger
- [ ] Config and packaging for cluster deployment
- [ ] Testing, refactoring, documentation
- [ ] Integrate template changes into a solution
