### ISSUE TITLE
API Template and LB Pkg - All Polling Processes Must be Stateless

### ISSUE THREAD

**Issue by slathrop** [vuepointjs/pm-v1.0-beta#28]
### Background
- To support load balancing and HA we can't have "state" info or built-in jobs in pods/instances (e.g., doing a pull from another REST API), etc.
- [Microsoft Flow](https://flow.microsoft.com/en-us/) recommended scheduling engine to kick-off polling intervals

### Tasks
- [ ] Research best way to implement LB custom method endpoints
  - Consider security requirements
- [ ] Research how to securely call LB from MS Flow
  - Previous MS Flow stories assumed direct database access
  - This story *could* be implemented by having MS Flow insert a row in a database table, however, this would require that LB processes continue to poll the DB, and would therefore introduce potential for race conditions between multiple instances of LB
- [ ] Consider if this can be implemented in metadata-/model-driven fashion
- [ ] Get initial implementation working
- [ ] Testing, refactoring, documentation
- [ ] Integrate template changes into a solution
