### ISSUE TITLE
App Template and UI Pkg - Refactor Items Grid View Into Components

### ISSUE THREAD

**Issue by slathrop** [vuepointjs/pm-v1.0-beta#3]
### Background
- Items Grid View component currently (as of 1.0.0-alpha.23) has the code for multiple other components embedded in it (to deliver initial end-to-end, working alpha quickly)
  - And there are inflexible pieces of code for things like building search/count URLs
- For testability, maintainability, extensibility, and quality the code *must* be refactored out

### Tasks
- [x] Refactor REST API URL-builder code to support reqs for multi-column search, more filters/views, etc.
- [ ] Factor out applet items grid toolbar component (ItemsGridToolbar)
  - Reduce markup boilerplate by driving buttons from data/model
- [ ] Factor out applet items view menu component (ItemsGridViewsMenu)
- [ ] Factor out applet item details component (ItemDetailsPopup)
  - Implement "dirty check" confirmation popup on "Cancel" with changes
- [ ] Factor out common logic to helpers or other non-visual component
- [ ] Testing, documentation
- [ ] Integrate template changes into a solution
