### ISSUE TITLE
App Template and UI Pkg - Applet Nav As Tabs

### ISSUE THREAD

**Issue by slathrop** [vuepointjs/pm-v1.0-beta#31]
### Background
- As a follow-on to #22, instead of (or in addition to) simply docking the launcher menu, consider arranging applet icons horizontally under "suite bar" and have them function as "tabs"

### Tasks
- [x] Implement basic support for (optionally) rendering horizontally (no responsiveness, no conditional content in launcher menu, etc.)
- [x] Implement changes to overall global navigation to accommodate "tabs" area
- [x] Consider, design, implement metadata for configuring this approach and toggling on/off, etc.
- [x] Testing, refactoring, documentation
- [x] Integrate template changes into a solution
