### ISSUE TITLE
App Template and UI Pkg - Refactor Kbd Shortcuts For Global Scope, Menu State

### ISSUE THREAD

**Issue by slathrop** [vuepointjs/pm-v1.0-beta#4]
### Background
- Keyboard shortcuts are *critical* not only for end-user productivity, but also for dev efficiency in manual testing
  - They also pave the way for simple automated end-to-end (e2e) testing in the future
- Currently kbd shortcut implementation is scoped too narrowly (e.g., when input focus is in a textbox global kbd shortcuts won't fire)
- And currently kbd shortcuts don't handle global menu state properly (shortcut to open one menu must close all other menus, etc.)

### Tasks
- [ ] Refactor kbd shortcut component to use global binding
- [ ] Refactor kbd and global UI state mgmt to account for menus, etc.
- [ ] Refactor existing kbd shortcut mount/unmount and event handlers
- [ ] Testing, documentation
- [ ] Integrate template changes into a solution
