### ISSUE TITLE
App Template and UI Pkg - Confirmation Popup Component, Delete Item Action, Undelete and Recycle Bin View

### ISSUE THREAD

**Issue by slathrop** [vuepointjs/pm-v1.0-beta#5]
### Tasks
- [ ] Implement reusable confirmation popup component
- [ ] Use component to implement item delete (archive) confirmation
- [ ] Implement admin-only undelete (restore from recycle bin) feature
  - Reactive items grid toolbar buttons based on current view
  - For now, everyone an admin, but lay groundwork for RBAC-based availability of feature
- [ ] Testing, documentation
- [ ] Integrate template changes into a solution
