### ISSUE TITLE
API Template and LB Pkg - Azure AD Signing Key Auto-refresh

### ISSUE THREAD

**Issue by slathrop** [vuepointjs/pm-v1.0-beta#6]
### Tasks
- [ ] Add LoopBack data source for querying MS endpoint containing JSON Web Key Set (JWK Set aka JWKS)
  - Example LB connection available. MS endpoint datasource will be very similar. LoopBack docs are [here](https://loopback.io/doc/en/lb3/REST-connector.html)
  - Endpoint: https://login.microsoftonline.com/common/discovery/keys
- [ ] Every time we need to [verify a JWT](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-token-and-claims#validating-the-signature) we should attempt to read from an in-memory cache, which should use a [read-through cache approach](https://en.wiktionary.org/wiki/read-through), hitting the endpoint (again) whenever a matching thumbprint (x5t) for the public key certificate (x5c) does not exist in the in-memory cache
  - Microsoft's [docs](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-token-and-claims#validating-the-signature) say that in general the public key certificates are good for at least 24 hours
  - But instead of using a 24 hour timer or any sort of polling, we might as well simply use the read-through cache approach (at the time of JWT validation/verification)
- [ ] Testing, documentation
- [ ] Integrate template changes into a solution

### For further reference:
https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-signing-key-rollover
https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-token-and-claims#validating-the-signature
https://auth0.com/docs/jwks
https://tools.ietf.org/html/rfc7517
https://tools.ietf.org/html/draft-ietf-jose-json-web-key
https://en.wiktionary.org/wiki/read-through
https://auth0.com/docs/jwks#verifying-a-jwt-using-the-jwks-endpoint
