### ISSUE TITLE
Solution Data, App Template, UI Pkg - Items Grid Multi-Column Search

### ISSUE THREAD

**Issue by slathrop** [vuepointjs/pm-v1.0-beta#7]
### Tasks
- [x] Design metadata schema to support configurable search properties/columns
- [x] Use refactored URL-builder code as basis to develop metadata-driven (View specs) search (and count) per applet and view
  - New piece is the "OR" condition: **where LName like 'zzz' OR Email like 'zzz'**
  - [x] Search REST API URL builder logic
  - [x] Count REST API URL builder logic (count syntax is slightly different)
    - [x] Optimize by sending count back in response header of search API call
- [x] Testing, refactoring, documentation
- [x] Integrate template changes into a solution

### Next Steps
- Must implement admin site and refactored metadata schema to expose this feature to admin users
