### ISSUE TITLE
App Template and UI Pkg - Applet Items Grid View Columns More Complete Support for all Field Types

### ISSUE THREAD

**Issue by slathrop** [vuepointjs/pm-v1.0-beta#8]
### Tasks
- [ ] Add any necessary metadata to configure desired column rendering beyond what the datatype currently conveys
- [ ] Implement rendering for known-missing types
  - [ ] Date
  - [ ] Datetime
  - [ ] Categorical value lookup
  - [ ] Numeric: int, money
  - [ ] Formatted string: phone, etc.
  - [ ] References (users, other foreign keys)
- [ ] Research/consider any other use-cases
- [ ] Testing, refactoring, documentation
- [ ] Integrate template changes into a solution
