### ISSUE TITLE
App Template and UI Pkg - Applet Items Grid View Columns Advanced Rendering Option for Categorical Field Types

### ISSUE THREAD

**Issue by slathrop** [vuepointjs/pm-v1.0-beta#9]
### Background
- Users of SharePoint, O365, and ERP/CRM systems have come to expect at-a-glance color-coding (background color) of table cells based on status
  - For example: Item Status "Created" = Red, "In Process" = Yellow, "Complete" = Green

### Tasks
- [ ] Add any necessary metadata to configure desired categorical column color coding
- [ ] Implement color-coded rendering for
  - [ ] Categorical values (status)
- [ ] Testing, refactoring, documentation
- [ ] Integrate template changes into a solution
